kind:               PersistentVolumeClaim
apiVersion:         v1
metadata:
  name:             mypvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage:      200Mi
